openapi: 3.0.0
info:
  title:  Hello Name
  description:  Hello name
  version: 1.0.0
servers:
  - url: http://0.0.0.0
paths:
  /api/hello/{name}:
    get:
      summary:  Hello
      parameters:
        - name: name
          in: path
          required: true
          description: name
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello Pavel

